{% set name = "mkdocstrings" %}
{% set version = "0.15.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocstrings-{{ version }}.tar.gz
  sha256: 32d10df8a38c133772fd322008cd531831aac7ea7fc40a6831d696a262c1659e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry
  run:
    - jinja2 >=2.11,<3.0
    - markdown >=3.3,<4.0
    - markupsafe >=1.1,<2.0
    - mkdocs >=1.1,<2.0
    - mkdocs-autorefs >=0.1,<0.2
    - pymdown-extensions >=6.3,<9.0
    - python >=3.6,<4.0
    - pytkdocs >=0.2.0,<0.12.0

test:
  imports:
    - mkdocstrings
    - mkdocstrings.handlers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mkdocstrings/mkdocstrings
  summary: Automatic documentation from sources, for MkDocs.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
    - hadim
