{% set name = "mkdocstrings" %}
{% set version = "0.14.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocstrings-{{ version }}.tar.gz
  sha256: f1b832943c4fe980fcfc17d07abfe9a8091044dbf553cb7be0ca263953130b2c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<4.0
  run:
    - beautifulsoup4 >=4.8.2
    - mkdocs >=1.1
    - pymdown-extensions >=6.3,<9.0
    - python >=3.6,<4.0
    - pytkdocs >=0.2.0,<0.10.0

test:
  imports:
    - mkdocstrings
    - mkdocstrings.handlers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pawamoy/mkdocstrings
  summary: Automatic documentation from sources, for MkDocs.
  license: ISC (ISCL)
  license_family: Other
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
