{% set name = "mkdocstrings" %}
{% set version = "0.16.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocstrings-{{ version }}.tar.gz
  sha256: 3d8a86c283dfa21818d5b9579aa4e750eea6b5c127b43ad8b00cebbfb7f9634e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - pdm-pep517
  run:
    - jinja2 >=2.11.1,<4.0
    - markdown >=3.3,<4.0
    - markupsafe >=1.1,<3.0
    - mkdocs >=1.2,<2.0
    - mkdocs-autorefs >=0.1,<0.4
    - pymdown-extensions >=6.3,<10.0
    - python >=3.6,<4.0
    - pytkdocs >=0.2.0,<0.13.0

test:
  imports:
    - mkdocstrings
    - mkdocstrings.handlers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mkdocstrings/mkdocstrings
  summary: Automatic documentation from sources, for MkDocs.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
    - hadim
