{% set name = "mkdocstrings" %}
{% set version = "0.19.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocstrings-{{ version }}.tar.gz
  sha256: efa34a67bad11229d532d89f6836a8a215937548623b64f3698a1df62e01cc3e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<4.0
    - pdm-pep517
  run:
    - python >=3.7,<4.0
    - jinja2 >=2.11.1
    - markdown >=3.3
    - markupsafe >=1.1
    - mkdocs >=1.2
    - mkdocs-autorefs >=0.3.1
    - pymdown-extensions >=6.3
    - mkdocstrings-python-legacy >=0.2

test:
  imports:
    - mkdocstrings
    - mkdocstrings.handlers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mkdocstrings/mkdocstrings
  doc_url: https://mkdocstrings.github.io
  summary: Automatic documentation from sources, for MkDocs.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
    - hadim
